package mx.ine.gestiona_t.modules.auditoria.model.enums;

public enum TipoEvento {
    // AUTH
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    REGISTRO_INICIADO,
    REGISTRO_COMPLETADO,
    OTP_GENERADO,
    OTP_VALIDADO,
    OTP_FALLIDO,
    CUENTA_BLOQUEADA,
    TOKEN_INVALIDO,
    LOGOUT,
    
    // CV
    CV_CREADO,
    CV_ACTUALIZADO,
    CV_ELIMINADO,
    ESCOLARIDAD_AGREGADA,
    EXPERIENCIA_AGREGADA,
    CURSO_AGREGADO,
    HABILIDAD_AGREGADA,
    CV_CARGADO_NO_ESTRUCTURADO,
    
    // DOCUMENTOS
    DOCUMENTO_CARGADO,
    DOCUMENTO_CLASIFICADO,
    DOCUMENTO_VALIDADO_TIPO_A,
    DOCUMENTO_VALIDADO_TIPO_B,
    DOCUMENTO_EN_REVISION,
    DOCUMENTO_RECHAZADO,
    DOCUMENTO_ELIMINADO,
    SFP_CONSULTADO,
    
    // MATCHING
    MATCHING_INICIADO,
    MATCHING_COMPLETADO,
    ANONIMIZACION_CV,
    EVALUACION_LOTE,
    
    // CARTA DECLARATORIA
    CARTA_INICIADA,
    BLOQUE_ACEPTADO,
    BLOQUES_COMPLETADOS,
    VALIDACION_EXTERNA_OK,
    VALIDACION_EXTERNA_RECHAZADA,
    CARTA_FIRMADA,
    
    // FIRMA
    FIRMA_SOLICITADA,
    FIRMA_FEA_COMPLETADA,
    FIRMA_BIOMETRICA_COMPLETADA,
    FIRMA_OTP_COMPLETADA,
    FIRMA_RECHAZADA,
    TIMESTAMP_SOLICITADO,
    
    // SEGURIDAD
    ACCESO_DENEGADO,
    RATE_LIMIT_EXCEDIDO,
    INTENTO_INYECCION,
    ARCHIVO_MALICIOSO_DETECTADO,
    CERTIFICADO_INVALIDO,
    
    // SISTEMA
    SERVICIO_INICIADO,
    SERVICIO_DETENIDO,
    ERROR_SISTEMA,
    BACKUP_COMPLETADO,
    SINCRONIZACION_CATALOGOS,
    
    // ADMIN
    CONFIGURACION_MODIFICADA,
    USUARIO_CREADO,
    USUARIO_MODIFICADO,
    ROL_ASIGNADO
}