package mx.ine.gestiona_t.modules.documentos.model.enums;

public enum TipoDocumento {
    CV,                             // ✅ AGREGADO: Currículum Vitae
    CEDULA_PROFESIONAL,
    CURP,
    RFC,
    ACTA_NACIMIENTO,
    IDENTIFICACION_OFICIAL,
    CERTIFICADO_BACHILLERATO,
    CERTIFICADO_MEDIO_SUPERIOR,
    CERTIFICACION_TECNICA,
    CONSTANCIA_LABORAL,
    EVALUACION_CONOCIMIENTOS,
    EVALUACION_PSICOMETRICA,
    EVALUACION_ENTREVISTA,
    COMPROBANTE_DOMICILIO,
    COMPROBANTE_SITUACION_FISCAL,
    FUM,
    TRES_CARTAS_RECOMENDACION,
    ALTA_ISSSTE,
    FOTOGRAFIA,
    FORMATO_INSCRIPCION_FONAC,
    FORMATO_GASTOS_FUNERARIOS,
    FORMATO_SEGURO_VIDA_INSTITUCIONAL,
    SOPORTE_EXPEDIENTE_LABORAL,
    OTRO
}